name: build
on: [push, pull_request]
jobs:
  pio-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: platformio/action-install@v1
      - name: Build MASTER
        run: pio run -e master
      - name: Build SLAVE1
        run: pio run -e slave1
      - name: Build SLAVE2
        run: pio run -e slave2
      - name: Build SLAVE3
        run: pio run -e slave3
